use_frameworks!
target 'ViewSizeCalculator_Tests' do
  pod 'ViewSizeCalculator', :path => '../'
end

target 'ViewSizeCalculator_Example' do
  pod 'ViewSizeCalculator', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
end
